// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEHVSx-fGGPL38Gxm67k9TIUpg8XJghg',
    appId: '1:914161097678:web:5bc5db0311ae7e173d699f',
    messagingSenderId: '914161097678',
    projectId: 'tiktok-clone-56520',
    authDomain: 'tiktok-clone-56520.firebaseapp.com',
    storageBucket: 'tiktok-clone-56520.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4tnbXMnncdQIDL5IkzuV0yCxyip7ToBU',
    appId: '1:914161097678:android:240ad75d2846a25d3d699f',
    messagingSenderId: '914161097678',
    projectId: 'tiktok-clone-56520',
    storageBucket: 'tiktok-clone-56520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMrenROugpibj-TNMPCd3zWUuyVaqjFbE',
    appId: '1:914161097678:ios:65dfd9b1f8cadfd63d699f',
    messagingSenderId: '914161097678',
    projectId: 'tiktok-clone-56520',
    storageBucket: 'tiktok-clone-56520.appspot.com',
    iosBundleId: 'com.example.tiktak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMrenROugpibj-TNMPCd3zWUuyVaqjFbE',
    appId: '1:914161097678:ios:65dfd9b1f8cadfd63d699f',
    messagingSenderId: '914161097678',
    projectId: 'tiktok-clone-56520',
    storageBucket: 'tiktok-clone-56520.appspot.com',
    iosBundleId: 'com.example.tiktak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuEHVSx-fGGPL38Gxm67k9TIUpg8XJghg',
    appId: '1:914161097678:web:d64dd1ac9a4197db3d699f',
    messagingSenderId: '914161097678',
    projectId: 'tiktok-clone-56520',
    authDomain: 'tiktok-clone-56520.firebaseapp.com',
    storageBucket: 'tiktok-clone-56520.appspot.com',
  );
}
